models/Category.php
<?php

namespace app\models;

use Yii;
use app\components\ActiveRecord;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use app\models\CategoryName;
use yii\helpers\Url;

class Category extends \yii\db\ActiveRecord
{
    public $category_name_all;
    
    public static function tableName()
    {
        return '{{%category}}';
    }

    public function scenarios()
    {
        return [
            'add_category' => ['name', 'slug', 'parent_id','img_src', 'position'],
            'default' => ['name', 'slug', 'parent_id','img_src', 'position']
        ];
    }
    
    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            'slug' => [
                'class'         => 'app\behaviors\Slug',
                'in_attribute'  => 'name',
                'out_attribute' => 'slug',
                'translit'      => true
            ]
        ];
    }
    
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['slug'], 'unique'],
        ];
    }
    
    public function beforeSave($insert)
    {
        if ($this->isNewRecord)
        {
            $this->date_create = date("Y-m-d H:i:s");
        }

        return parent::beforeSave($insert);
    }

    public function getImage()
    {
        return $this->img_src ? '/img/category/'.$this->img_src : null;
    }

    public function getChildcateogory()
    {
        return $this->hasMany(Category::className(), ['parent_id' => 'id'])->orderBy('name ASC');
    }
    
    public function getCategorynamemodel()
    {
        return $this->hasOne(CategoryName::className(), ['category_id' => 'id']);
    }
    
    public function getProductcount()
    {
        return Productcategory::find()->joinWith('product')->where(['product_category.category_id' => $this->id, 'product.status' => '1'])->count();
    }
    
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'Номер'),
            'name' => Yii::t('app', 'Название'),
            'slug' => Yii::t('app', 'Артикул'),
            'parent_id' => Yii::t('app', 'Родительская категория'),
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);
        $this->saveCategoryName();
    }
    
    public function saveCategoryName(){
        $modelCategoryname = $this->categorynamemodel;
        if(!$modelCategoryname){
            $modelCategoryname = new CategoryName();
            $modelCategoryname->category_id = $this->id;
        }

        $modelCategoryname->name = $this->СategoryName($this->id);
        $modelCategoryname->save();
    }
    
    public function СategoryName($category_id){
        $modelCategory = Category::find()->where(['id' => $category_id])->one();
        if($modelCategory != null){
            if($this->category_name_all != ''){
                $this->category_name_all = $modelCategory->name.' -> '.$this->category_name_all;                
            }else{
                $this->category_name_all = $modelCategory->name;
            }
            if($modelCategory->parent_id != 0){
                $this->СategoryName($modelCategory->parent_id);                
            }
        }
        return $this->category_name_all;
    }

}

controllers/CategoryController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\User;
use app\models\Category;
use app\models\Product;
use app\models\RegForm;
use app\models\Attribute;
use app\models\Profile;
use app\models\Productcategory;
use app\models\SendEmailForm;
use app\models\ResetPasswordForm;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use app\models\AccountActivation;
use yii\data\ActiveDataProvider;
use yii\db\Query;

class CategoryController extends Controller
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function beforeAction($action) {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex($category_slug)
    {
        $modelParentCategory = Category::find()->where(['slug' => $category_slug])->one();
        $modelCategory = Category::find()->where(['parent_id' => $modelParentCategory->id])->orderBy('position ASC')->asArray()->all();
        $categoryArray = [];
        foreach($modelCategory as $category){
            $modelChildCategory = Category::find()->where(['parent_id' => $category['id']])->asArray()->all();
            $categoryArray[] = ['category_info' => $category, 'category_child' => $modelChildCategory];            
        }
        
        if($modelParentCategory != null){
            return $this->render('index',[
                'categoryArray' => $categoryArray,
                'modelParentCategory' => $modelParentCategory,
            ]);
        }else{
            throw new \yii\web\NotFoundHttpException();
        }
    }
    
    public function actionCategory($category_slug)
    {
        $modelCategory = Category::find()->where(['slug' => $category_slug])->one();

        $arrayCategory = [];
        $arrayCategory['category'] = $modelCategory;
        if($modelCategory){
            if($modelCategory->parent_id != 0){
                $modelParentCategory = Category::find()->where(['id' => $modelCategory->parent_id])->one();
                $arrayCategory['parent'] = $modelParentCategory;
                
                if($modelParentCategory->parent_id){
                    $modelParentParentCategory = Category::find()->where(['id' => $modelParentCategory->parent_id])->one();
                    $arrayCategory['parent_parent'] = $modelParentParentCategory;
                }
            }
            $modelChildCategory = Category::find()->where(['parent_id' => $modelCategory->id])->orderBy('position ASC')->all();
            
//            $query = new Query();
//            $query->select(['*', 'id' => '{{%product}}.id'])
//                        ->from('{{product_category}}')
//                        ->join('LEFT JOIN',
//                                        '{{%product}}',
//                                        '{{%product}}.id = {{%product_category}}.product_id'
//                                )->where(['{{%product_category}}.category_id' => $modelCategory->id]);
//                        
//            $modelProduct = new ActiveDataProvider(['query' => $query, 'pagination' => ['pageSize' => 10]]);
            return $this->render('category',[
                'arrayCategory' => $arrayCategory,
                'modelChildCategory' => $modelChildCategory,
                //'productCount' => $productCount,
//                'modelProduct' => $modelProduct->getModels(),
//                'pagination' => $modelProduct->pagination,
            ]);
        }else{
            throw new \yii\web\NotFoundHttpException();
        }
    }
    
    public function actionSubcategory($category_slug)
    {
        $modelCategory = Category::find()->where(['slug' => $category_slug])->one();
        $query = Product::find()->where(['category_id' => $modelCategory['id']]);
        $productCount = $query->count();
        $modelProduct = new ActiveDataProvider(['query' => $query, 'pagination' => ['pageSize' => 10]]);
        exit;
        if($modelCategory != null){
            return $this->render('subcategory',[
                'productCount' => $productCount,
                'modelProduct' => $modelProduct->getModels(),
                'pagination' => $modelProduct->pagination,
                'modelCategory' => $modelCategory,
            ]);
        }else{
            throw new \yii\web\NotFoundHttpException();
        }
    }
    
    public function actionGetchildcategory()
    {
        $category_id = $_POST['category_id'];
        $modelCategories = Category::find()->where(['parent_id' => $category_id])->orderBy('position ASC')->asArray()->all();
        if($modelCategories != null){
            $result['data'] = ArrayHelper::map($modelCategories,'id','name');
            $result['type'] = 'child_category';
            $result['status'] = 'success';
        }else{
            $modelAttribute = Attribute::find()->where(['category_id' => $category_id])->asArray()->all();
            if($modelAttribute != null){
                $result['data'] = $modelAttribute;
                $result['type'] = 'attribute';
                $result['status'] = 'success';
            }else{
                $result['status'] = 'error';
            }
        }
        
        echo json_encode($result);
    }
}

views/category/category.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\LinkPager;
use app\assets\ProductsAsset;

ProductsAsset::register($this);
$this->registerJsFile('/js/socket.io-1.3.5.js');
$this->registerJsFile('/js/userOnline.js');

?>
<div class="main-content">
    <div>
        <div style="text-align: left;padding:10px 0px">
            <?php if (isset($arrayCategory['parent_parent'])) { ?>
                <a href="<?= Url::home(); ?>category/<?= $arrayCategory['parent_parent']->slug; ?>"
                   class="app_breadcrumb">
                    <b> <?= $arrayCategory['parent_parent']->name; ?></b>
                </a>  <img class="img-split" src="/img/arrow-right.png" alt="">
            <?php } ?>
            <?php if (isset($arrayCategory['parent'])) { ?>
                <a href="<?= Url::home(); ?>category/<?= $arrayCategory['parent']->slug; ?>" class="app_breadcrumb">
                    <b><?= $arrayCategory['parent']->name; ?></b>
                </a>  <img class="img-split" src="/img/arrow-right.png" alt="">
                <a href="<?= Url::home(); ?>category/<?= $arrayCategory['category']->slug; ?>" class="app_breadcrumb">
                    <b><?= $arrayCategory['category']->name; ?></b>
                </a>
            <?php } else { ?>
                <a class="app_breadcrumb">
                    <?= $arrayCategory['category']->name; ?>
                </a>
            <?php } ?>
        </div>
<!--        --><?php //if ($arrayCategory['category']->img_src != '') { ?>
<!--            <img class="img_product" src="--><?//= Url::home() . 'img/category/' . $arrayCategory['category']->img_src; ?><!--">-->
<!--        --><?php //} else { ?>
<!--            <img src="">-->
<!--        --><?php //} ?>

        <!--        <h1 style="font: 25px 'Lato';text-align:left;font-weight: 900;padding:15px 0;">-->
        <!--            --><? //= $arrayCategory['category']->name; ?>
        <!--        </h1>-->
        <div>
            <ul class="childCategoryC">
                <?php foreach ($modelChildCategory as $child_category) { ?>
                    <li><a  href="/category/<?= $child_category->slug; ?>">
                            <div class="img_category_child"
                                     style="<?= $child_category->getImage() ? 'background: url('.$child_category->getImage().') center no-repeat;' : '' ?>; background-size: cover;background-color: black;">
                                </div>
                            <div class="img_category_bacg_black3"></div>
                                <span class="div_category_child_name"><?= $child_category->name; ?><em> (<?= $child_category->productcount; ?>)</em></span>
                            <div class="block">
                                <div class="img_category_child2"
                                     style="<?= $child_category->getImage() ? 'background: url('.$child_category->getImage().') center no-repeat;' : '' ?>; background-size: cover;background-color: black;">
                                </div>
                                <div class="img_category_bacg_black"></div>
                                <span class="div_category_child_name2"><?= $child_category->name; ?><em> (<?= $child_category->productcount; ?>)</em></span>
                            </div>
                        </a>
                    </li>
                <?php } ?>
            </ul>
            <div style="clear:both;"></div>
        </div>
    </div>

    <div>
        <a class="show_product_filter hidden-sm hidden-md hidden-lg ">Развернуть фильтры поиска</a>
        <a class="hide_product_filter hidden-sm hidden-md hidden-lg " style="display:none;">Свернуть фильтры поиска</a>
        <div class="row no_margin FilterBlock ">
            <input type="hidden" name="filter_category_id" value="<?= $arrayCategory['category']->id; ?>">
            <div class="app_filter-price">
                <div class="filter-title">Цена:</div>
                <div class="form_group col-md-5 no_padding">
                    <input type="text" name="filter_price_from" placeholder="От">
                </div>
                <div class="form_group col-md-5 no_padding">
                    <input type="text" name="filter_price_to" placeholder="До">
                </div>
                <div class="form_group col-md-2 no_padding">
                    <span>руб.</span>
                </div>
            </div>
            <div class="app_filter-time">
                <div class="filter-title">Срок размещения:</div>
                <div class="form_group col-md-3 no_padding">
                    <input type="radio" id="f_24" name="filter_date_to" value="1">
                    <label for="f_24" class="radio-inline"> за 24 часа</label>
                </div>
                <div class="form_group col-md-3 no_padding">
                    <input type="radio" id="f_7" name="filter_date_to" value="7">
                    <label for="f_7" class="radio-inline"> за 7 дней</label>
                </div>
                <div class="form_group col-md-3 no_padding">
                    <input type="radio" id="f_30" name="filter_date_to" value="30">
                    <label for="f_30" class="radio-inline"> за 30 дней</label>
                </div>
                <div class="form_group col-md-3 no_padding">
                    <input type="radio" id="f_all" name="filter_date_to" value="all" checked="checked">
                    <label for="f_all" class="radio-inline"> за все время</label>
                </div>
            </div>
            <div class="app_filter-sort">
                <div class="filter-title">Сортировка:</div>
                <div class="form_group col-md-7 no_padding">
                    <input type="radio" id="f_date" name="filter_sort" value="date">
                    <label for="f_date" class="radio-inline"> по дате публикации</label>
                </div>
                <div class="form_group col-md-5 no_padding">
                    <input type="radio" id="f_price" name="filter_sort" value="price" checked="checked">
                    <label for="f_price" class="radio-inline"> по стоимости</label>
                </div>
            </div>
        </div>
    </div>
    <div style="padding-top:18px;text-align:right;padding-right:8px;">
        <span class="filter-title">Показать объявления</span>
        <div class="gridStyle" style="display:inline-block;">
            <img src="/img/show_grid.png" style="width:16px;"/>
        </div>
        <div class="listStyle" style="display:inline-block;">
            <img src="/img/show_list.png" style="width:16px;"/>
        </div>
    </div>
    <div class="main-catalog col-sm-12 productsBlock" style="padding-left: 0px;padding-right:0px;">
    </div>
    <div style="text-align: center">
        <a class="show_more_product_btn">Больше товаров</a>
    </div>
</div>

views/category/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

?>

<div class="select-cat">
        <div class="container">
                <div class="sel-cat-list clearfix">
                        <div class="cat-avto_title mobile">
                                <h1>Категория <?= $modelParentCategory->name; ?></h1>
                        </div>
                        <div class="select-cat_title">
                                <span>Выбор по категориям</span>
                        </div>
                        <ul>
                                    <?php foreach($categoryArray as $category){ ?>
                                        <li>
                                        <?= HTML::a($category['category_info']['name'], '#'); ?>
                                        </li>
                                    <?php } ?>
                        </ul>
                </div>

                <?php foreach($categoryArray as $category){ ?>
                    <div class="select-cat_item">
                        <div class="cat-item_img">
                            <?php if($category['category_info']['img_src'] == ''){ ?>
                                <img src="<?= Url::home().'img/category/default_img.png' ?>" alt="" style="max-width: 50px;margin-bottom: 5px;max-height: 50px;">
                            <?php }else{ ?>
                                <img src="<?= Url::home().'img/category/'.$category['category_info']['name']; ?>" alt="" style="max-width: 50px;margin-bottom: 5px;max-height: 50px;">
                            <?php } ?>
                                <?= HTML::a($category['category_info']['name'], Url::home().'category/'.$category['category_info']['slug']); ?>
                        </div>
                        <div class="cat-item_list">
                                <ul>
                                    <?php foreach($category['category_child'] as $child_category){ ?>
                                        <li>
                                            <?= HTML::a($child_category['name'], Url::home().'subcategory/'.$child_category['slug']); ?>
                                        </li>
                                    <?php } ?>
                                </ul>
                        </div>
                        <div style="clear:both;"></div>
                    </div>
                <?php } ?>

        </div>
</div>

views/category/subcategory.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\LinkPager;
?>

	<div class="search-result clearfix">
		<div class="container">
			<span class="search-result_title">Найдено <?= $productCount; ?> обьявления</span>
			<?php foreach($modelProduct as $product){ ?>
                            <div class="result-item">
                                    <div class="item-img">
                                        <?php if($product->img_src != ''){ ?>
                                                <img src="<?= Url::home().'img/product/'.$product->img_src; ?>" alt="">
                                        <?php }else{ ?>
                                                <img src="<?= Url::home(); ?>img/DefaultFotoProduct.png" alt="">
                                        <?php } ?>
                                    </div>
                                    <div class="item-head">
                                            <?= HTML::a($product->title,Url::home().'product/'.$product->id); ?>
                                            <span class="date-item"><?= $product->date_create; ?></span>
                                    </div>
                                    <div class="item-main">
                                            <p><?= $product->about; ?></p>
                                    </div>
                                    <div class="item-foot">
                                            <!--<div class="release-year">Год выпуска:<span>2013</span></div>
                                            <div class="mileage">Состояние:<span>После кап. ремонта</span></div>-->
                                            <div class="price-item"><?= $product->price; ?>руб</div>
                                    </div>
                            </div>
                        <?php } ?>
			
			<div class="pagination">
                            <?= LinkPager::widget(['pagination'=>$pagination]); ?>
			</div>
		</div>
        </div>